services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BookManager2-master/book_manager.sql:/docker-entrypoint-initdb.d/book_manager.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
